export type Standard = {
  title: string;
  url: string;
};
export const STANDARDS = {
  astmF2761: { title: 'ASTM F2761', url: 'https://www.astm.org/f2761-09r20.html' },
  bacnet: { title: 'BACnet', url: 'https://www.bacnet.org/' },
  bot: { title: 'BOT', url: 'https://w3c-lbd-cg.github.io/bot/' },
  coap: { title: 'CoAP', url: 'https://www.rfc-editor.org/rfc/rfc7252' },
  cyclonedx: { title: 'CycloneDX', url: 'https://cyclonedx.org/' },
  dds: { title: 'DDS', url: 'https://www.omg.org/spec/DDS/' },
  fhir: { title: 'HL7 FHIR', url: 'https://hl7.org/fhir/' },
  fiveG: { title: '5G', url: 'https://www.3gpp.org/technologies/5g-system-overview' },
  geolocation: { title: 'W3C Geolocation API', url: 'https://www.w3.org/TR/geolocation/' },
  gs1: { title: 'GS1 Standards', url: 'https://www.gs1.org/standards' },
  iec61850: { title: 'IEC 61850', url: 'https://www.iec.ch/smartgrid/standards/' },
  ieee1547: { title: 'IEEE 1547', url: 'https://standards.ieee.org/ieee/1547/5915/' },
  ifc: { title: 'IFC', url: 'https://technical.buildingsmart.org/standards/ifc/' },
  jsonLd: { title: 'JSON-LD', url: 'https://www.w3.org/TR/json-ld11/' },
  knx: { title: 'KNX', url: 'https://www.knx.org/knx-en/for-professionals/benefits/knx-standard/' },
  loraWan: { title: 'LoRaWAN', url: 'https://lora-alliance.org/about-lorawan/' },
  matter: { title: 'Matter', url: 'https://csa-iot.org/all-solutions/matter/' },
  modbus: { title: 'Modbus', url: 'https://modbus.org' },
  mqtt: { title: 'MQTT', url: 'https://mqtt.org/' },
  nbIot: { title: 'NB-IoT', url: 'https://www.3gpp.org/technologies/nb-iot' },
  nmea: { title: 'NMEA 0183', url: 'https://www.nmea.org/content/STANDARDS/NMEA_0183_Standard' },
  oauth2: { title: 'OAuth 2.0', url: 'https://www.rfc-editor.org/rfc/rfc6749' },
  ogc: { title: 'OGC Standards', url: 'https://www.ogc.org/standards/' },
  opcUa: { title: 'OPC UA', url: 'https://opcfoundation.org/about/opc-technologies/opc-ua/' },
  openidConnect: { title: 'OpenID Connect', url: 'https://openid.net/developers/how-connect-works/' },
  profinet: { title: 'PROFINET', url: 'https://www.profibus.com/technology/profinet' },
  rdf: { title: 'RDF', url: 'https://www.w3.org/TR/rdf12-concepts/' },
  saref: { title: 'SAREF', url: 'https://saref.etsi.org/' },
  saref4agri: { title: 'SAREF4AGRI', url: 'https://saref.etsi.org/saref4agri/' },
  saref4bldg: { title: 'SAREF4BLDG', url: 'https://saref.etsi.org/saref4bldg/' },
  saref4ener: { title: 'SAREF4ENER', url: 'https://saref.etsi.org/saref4ener/' },
  sdi12: { title: 'SDI-12', url: 'https://www.sdi-12.org/' },
  sensorThings: { title: 'OGC SensorThings API', url: 'https://www.ogc.org/standards/sensorthings/' },
  spdx: { title: 'SPDX', url: 'https://spdx.dev/' },
  sparql: { title: 'SPARQL', url: 'https://www.w3.org/TR/sparql11-query/' },
  ssnSosa: { title: 'SSN/SOSA', url: 'https://www.w3.org/TR/vocab-ssn/' },
  tls13: { title: 'TLS 1.3', url: 'https://www.rfc-editor.org/rfc/rfc8446' },
  webSocket: { title: 'WebSocket', url: 'https://www.rfc-editor.org/rfc/rfc6455' },
  x509: { title: 'X.509', url: 'https://www.itu.int/rec/T-REC-X.509' },
  zigbee: { title: 'Zigbee', url: 'https://csa-iot.org/all-solutions/zigbee/' },
  zwave: { title: 'Z-Wave', url: 'https://z-wavealliance.org/z-wave-specification/' },
} satisfies Record<string, Standard>;
