interface RESEARCH_PAPER {
  title: string;
  url: string;
  authors: string[];
  publisher: string;
  date: string;
}

export const RESEARCH_PAPERS: RESEARCH_PAPER[] = [
  {
    title: 'Methodologies in digital twin for manufacturing industry: A systematic literature review',
    url: 'https://www.sciencedirect.com/science/article/pii/S0167739X25002924',
    authors: ['G. A. Lapuente', 'P. M. Avinzano', 'M. P. L. Castillo', 'et al.'],
    publisher: 'Future Generation Computer Systems (Elsevier)',
    date: '2026',
  },
  {
    title:
      'Increasing interoperability between digital twin standards and specifications: transformation of DTDL to AAS',
    url: 'https://www.mdpi.com/1424-8220/23/18/7742',
    authors: ['C. Schmidt', 'F. Volz', 'L. Stojanovic', 'G. Sutschet'],
    publisher: 'Sensors (MDPI)',
    date: '2023',
  },
  {
    title:
      'Internet of Things: A comprehensive survey on syntactic and semantic interoperability for effective inter-entity communication',
    url: 'https://www.sciencedirect.com/science/article/pii/S2590005626002651',
    authors: ['M. S. E. de la Parte', 'J. F. Martínez-Ortega', 'Y. Wang', 'et al.'],
    publisher: 'Array (Elsevier)',
    date: '2026',
  },
  {
    title: 'Overview and comparison of asset information model standards',
    url: 'https://ieeexplore.ieee.org/abstract/document/10239408/',
    authors: ['T. Miny', 'M. Thies', 'L. Lukic', 'S. Käbisch', 'K. Oladipupo', 'et al.'],
    publisher: 'IEEE',
    date: '2023',
  },
  {
    title: 'DTAG: A methodology for aggregating digital twins using the WoTDT ontology',
    url: 'https://www.mdpi.com/2076-3417/14/13/5960',
    authors: ['S. González-Gerpe', 'M. Poveda-Villalón', 'et al.'],
    publisher: 'Applied Sciences (MDPI)',
    date: '2024',
  },
  {
    title: 'Machine component monitoring in data and service ecosystems enabled by the asset administration shell',
    url: 'https://www.sciencedirect.com/science/article/pii/S2212827124014264',
    authors: ['V. Berchtenbreiter', 'T. Schröder', 'F. Gast', 'O. Kohn', 'et al.'],
    publisher: 'Procedia CIRP (Elsevier)',
    date: '2024',
  },
  {
    title: 'Decentralized authentication for web of things: a self-sovereign identity (SSI)-based solution',
    url: 'http://www.conf-icnc.org/2024/papers/p684-boi.pdf',
    authors: ['B. Boi', 'C. Esposito'],
    publisher: 'International Conference on Computing, Networking and Communications (ICNC)',
    date: '2024',
  },
  {
    title:
      'Cyberlogic: A Foundational Framework for Cross-Space Logic in the Cyber-Physical-Social-Thinking Hyperspace',
    url: 'https://ieeexplore.ieee.org/abstract/document/11543299/',
    authors: ['H. Ning', 'L. Zhou', 'J. W. Ayana', 'S. Cui', 'et al.'],
    publisher: 'IEEE Internet of Things Journal',
    date: '2026',
  },
  {
    title: 'HoloWoT: a first step towards mixed reality digital twins for the industrial internet of things',
    url: 'https://dl.acm.org/doi/abs/10.1145/3652620.3688243',
    authors: ['F. Salama', 'I. Sezgin', 'E. Korkan', 'S. Käbisch', 'et al.'],
    publisher: 'ACM',
    date: '2024',
  },
  {
    title: 'WoT2Pod: an architecture enabling an edge-to-cloud continuum',
    url: 'https://dl.acm.org/doi/abs/10.1145/3627050.3627063',
    authors: ['M. Freund', 'J. Fries', 'R. Dorsch', 'P. Schiller', 'et al.'],
    publisher: 'ACM',
    date: '2023',
  },
  {
    title: 'Proximity-based service discovery for distributed digital twin systems',
    url: 'https://link.springer.com/article/10.1007/s43926-025-00103-x',
    authors: ['K. Rothermel', 'O. Herzog', 'S. W. Zhiqiang'],
    publisher: 'Discover Internet of Things (Springer)',
    date: '2025',
  },
  {
    title: 'The Arrowhead Framework Ontology',
    url: 'https://ieeexplore.ieee.org/abstract/document/11517481/',
    authors: ['O. Wintercorn', 'J. van Deventer'],
    publisher: 'IEEE Open Journal of the Industrial Electronics Society',
    date: '2026',
  },
  {
    title: 'The SPA Ontology: Towards a Web of Things Ready for Robotic Agents',
    url: 'https://ceur-ws.org/Vol-3749/akr3-02.pdf',
    authors: ['M. Freund', 'D. Schraudner', 'S. Schmid', 'C. Stade', 'et al.'],
    publisher: 'ESWC (CEUR-WS)',
    date: '2024',
  },
  {
    title: 'WoT-Server: Combining the Web-Of-Things and SensorThings standards to build an IoT platform',
    url: 'https://joss.theoj.org/papers/10.21105/joss.09470.pdf',
    authors: ['J. Aumedes', 'X. Celades', 'J. Pijuan', 'et al.'],
    publisher: 'Journal of Open Source Software',
    date: '2026',
  },
  {
    title: 'RobWoT: Generating Real-Time Digital Twin Simulations for the Robotic Web of Things',
    url: 'https://ieeexplore.ieee.org/abstract/document/10539381/',
    authors: ['F. Salama', 'Z. Han', 'E. Korkan', 'S. Käbisch', 'et al.'],
    publisher: 'IEEE 9th World Forum on Internet of Things',
    date: '2023',
  },
  {
    title: 'From Fragmentation to Integration: A Framework for Heterogeneous IoT-based Smart City Systems',
    url: 'https://ieeexplore.ieee.org/abstract/document/11205783/',
    authors: ['T. A. Amorim', 'J. C. N. Bittencourt', 'D. G. Costa', 'et al.'],
    publisher: 'IEEE 30th International Conference',
    date: '2025',
  },
  {
    title: 'RobWoTAR: Web of Things Approach to Universally Control Robots in Augmented Reality',
    url: 'https://dl.acm.org/doi/abs/10.1145/3770501.3770526',
    authors: ['R. Binkert', 'A. Al-Hatem', 'F. Salama', 'E. Korkan', 'et al.'],
    publisher: 'ACM',
    date: '2025',
  },
  {
    title: 'Skill-Based Multi-Agent Systems for Building Control Using KNX IoT and Web of Things',
    url: 'https://ieeexplore.ieee.org/abstract/document/11205736/',
    authors: ['G. Steindl', 'T. Rapberger', 'et al.'],
    publisher: 'IEEE 30th International Conference',
    date: '2025',
  },
  {
    title: 'Asynchronous Thing Descriptions for Crafting Applications in the Web of Things',
    url: 'https://ieeexplore.ieee.org/abstract/document/11272525/',
    authors: ['M. Boliotis', 'A. Tzavaras', 'C. Tsinaraki', 'et al.'],
    publisher: 'IEEE 37th International Conference',
    date: '2025',
  },
  {
    title: 'RetroWoT: A Method to Integrate Brownfield Devices in the Web of Things',
    url: 'https://dl.acm.org/doi/abs/10.1145/3703790.3703799',
    authors: ['R. Dorsch', 'M. Freund', 'K. M. A. Arevalo', 'et al.'],
    publisher: 'ACM',
    date: '2024',
  },
  {
    title: 'Generating Visual Programming Blocks based on Semantics in W3C Thing Descriptions',
    url: 'https://ceur-ws.org/Vol-3412/paper1.pdf',
    authors: ['M. Freund', 'J. Fries', 'T. Wehr', 'A. Harth'],
    publisher: 'SWoCoT@ESWC (CEUR-WS)',
    date: '2023',
  },
  {
    title: 'Vendor-Independent Data Platform Architecture in Smart Buildings',
    url: 'https://ieeexplore.ieee.org/abstract/document/11366376/',
    authors: ['K. Matsukura', 'K. Noda', 'Y. Hashimoto', 'et al.'],
    publisher: 'IEEE 23rd International Conference',
    date: '2026',
  },
  {
    title: 'Stateful-WoT: Capturing the Behavior of Highly Dynamic Cyber-Physical Systems',
    url: 'https://ieeexplore.ieee.org/abstract/document/10622288/',
    authors: ['F. Salama', 'E. Korkan', 'S. Käbisch', 'et al.'],
    publisher: 'IEEE International Conference',
    date: '2024',
  },
  {
    title: 'Leveraging Information-Centric Edge Computing in Private 5G Cellular Networks via the W3C Web of Things',
    url: 'https://ieeexplore.ieee.org/abstract/document/10976001/',
    authors: ['J. Romann', 'H. H. Damer', 'T. M. R. Gias', 'et al.'],
    publisher: 'IEEE 22nd International Conference',
    date: '2025',
  },
  {
    title: 'A Model-Driven Framework for Heterogeneous IoT Systems',
    url: 'https://search.proquest.com/openview/6cfd69997cecacef39579569395b29aa/1?pq-origsite=gscholar&cbl=2026366&diss=y',
    authors: ['T. A. S. de Amorim'],
    publisher: 'ProQuest (Dissertation)',
    date: '2025',
  },
  {
    title: 'Knowledge graph construction and evolution using declarative mapping languages',
    url: 'http://oa.upm.es/83228/1/ANA_IGLESIAS_MOLINA.pdf',
    authors: ['A. Iglesias Molina'],
    publisher: 'Universidad Politécnica de Madrid',
    date: '2024',
  },
  {
    title: 'A Semantic Approach for Integrating Constrained MQTT Devices into Smart Local Energy Communities',
    url: 'https://repositum.tuwien.at/handle/20.500.12708/222001',
    authors: ['M. A. Thoma'],
    publisher: 'TU Wien',
    date: '2025',
  },
  {
    title:
      'Enriching RDF Data with LLM based Named Entity Recognition and Linking on Embedded Natural Language Annotations',
    url: 'https://paul.ti.rw.fau.de/~jo00defe/Enriching_RDF_Data_with_NER_and_EL_on_Natural_Language_Annotations.pdf',
    authors: ['A. Harth'],
    publisher: 'Friedrich-Alexander-Universität Erlangen-Nürnberg',
    date: '2024',
  },
  {
    title: 'D3.1 Initial Release of VOStack Layers and Intelligence Mechanisms on IoT Devices',
    url: 'https://nephele-project.eu/sites/nephele/files/public/content-files/deliverables/nephele_d3.1.pdf',
    authors: ['NTUA', 'ODINS', 'IBM', 'WINGS'],
    publisher: 'NEPHELE Project (Horizon Europe)',
    date: '2023',
  },
  {
    title: "Towards agents' embodiment in web-based multi-agent systems",
    url: 'https://amslaurea.unibo.it/id/eprint/31031/',
    authors: ['M. Castellucci'],
    publisher: 'University of Bologna',
    date: '2024',
  },
  {
    title: 'Web of Things',
    url: 'https://devopedia.org/web-of-things',
    authors: ['C. Room'],
    publisher: 'Devopedia',
    date: '2023',
  },
  {
    title: 'Standardisierte Maschinenanbindung an ein Produktionsleitsystem über die Asset Administration Shell',
    url: 'https://repo.bibliothek.uni-halle.de/bitstream/1981185920/113590/5/KommA2023_Tagungsband.pdf#page=175',
    authors: ['A. Schließmann', 'M. Stolze', 'et al.'],
    publisher: 'KommA 2023 (Martin Luther University Halle-Wittenberg)',
    date: '2023',
  },
];
