# frozen_string_literal: true

source "https://rubygems.org"

ruby '3.3.0'

# gem "rails"

gem "webrick", "~> 1.8"

gem 'jekyll', '~> 4.4', '>= 4.4.1'

gem 'csv', '~> 3.0'

gem 'base64', '~> 0.3.0'

gem 'bigdecimal', '~> 3.2', '>= 3.2.3'